services:
  - type: web
    name: cyber-portfolio-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: samuel
      - key: ADMIN_PASSWORD
        sync: false